% compile binaryInference opengm

mex CXXFLAGS="\$CXXFLAGS -fPIC" -I"../external/opengm/include" ...
 -I"../external/opengm/src/external/TRWS-v1.3.src-patched"...
 -I"../external/opengm/src/external/QPBO-v1.3.src-patched/" ...
 -L"../external/opengm/BUILD/src/external/" ...
 -lexternal-library-qpbo-shared ...
  binaryInference.cxx ... 
 -output binaryInference.mexa64
 